### ISSUE TITLE
Video embed codes are not generated consistently

### ISSUE THREAD

**Issue by areynold** [willpublicmedia/npr-cds-expressionengine#34]
When pulling stories with video, the `videoembed_grid` field is frequently empty in the final channel entry.

Review video markup generation and assignment to the `videoembed_grid` field.

Sample Story IDs:
- 579982124
- 673291531
- 622595890

CDS References:
- [has-videos](https://npr.github.io/content-distribution-service/api-reference/profiles/has-videos.html)
- [player-video](https://npr.github.io/content-distribution-service/api-reference/profiles/player-video.html)
- [stream-player-video](https://npr.github.io/content-distribution-service/api-reference/profiles/stream-player-video.html)
- [youtube-video](https://npr.github.io/content-distribution-service/api-reference/profiles/youtube-video.html)

**Comment by AdarshBhandari15** [comment]
Fixed in commit #36 (22b35e1ac98ce51183b7c2462ca75d120978f94e). This made issue #35 appear though.
